<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
	  <PackageId>WpfPluginKit</PackageId>
	  <Version>1.0.0</Version>
	  <Authors>RedSoundwave</Authors>
	  <Description>This template provides a structured approach for developing WPF plugins that include UI elements such as pages, windows, resources, and assets. The template ensures consistency across plugins and seamless integration with the main UI application.</Description>
	  <PackageTags>wpf, template</PackageTags>
	  <RepositoryUrl>https://github.com/RedSoundwave/WpfPluginKit</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MahApps.Metro.IconPacks" Version="5.1.0" />
    <PackageReference Include="WPF-UI" Version="4.0.2" />
    <PackageReference Include="WPF-UI.Tray" Version="4.0.2" />
  </ItemGroup>

	<ItemGroup>
		<Folder Include="Assets\" />
		<Folder Include="Behaviors\" />
		<Folder Include="Commands\" />
		<Folder Include="Converters\" />
		<Folder Include="Extensions\" />
		<Folder Include="Helpers\" />
		<Folder Include="Interfaces\" />
		<Folder Include="Localization\" />
		<Folder Include="Models\" />
		<Folder Include="Services\" />
		<Folder Include="Utility\" />
		<Folder Include="ViewModels\Windows\" />
		<Folder Include="ViewModels\Pages\" />
		<Folder Include="Views\" />
		<Folder Include="Views\Windows\" />
		<Folder Include="Views\Pages\" />
	</ItemGroup>

</Project>
